# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Text for filter tweets',
                'db_table': 'filter_text',
                'managed': False,
                'verbose_name_plural': 'Texts for filter tweets',
            },
        ),
        migrations.CreateModel(
            name='ReplyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Status reply',
                'db_table': 'reply_status',
                'managed': False,
                'verbose_name_plural': 'Statuses replies',
            },
        ),
        migrations.CreateModel(
            name='ReplyText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('count_use', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Text reply',
                'db_table': 'reply_text',
                'managed': False,
                'verbose_name_plural': 'Text replies',
            },
        ),
        migrations.CreateModel(
            name='RoleUserTwitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'User role',
                'db_table': 'role_user_twitter',
                'managed': False,
                'verbose_name_plural': 'Users roles',
            },
        ),
        migrations.CreateModel(
            name='StatusTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Status tweet',
                'db_table': 'status_tweet',
                'managed': False,
                'verbose_name_plural': 'Statuses tweets',
            },
        ),
        migrations.CreateModel(
            name='StatusUserTwitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'User status',
                'db_table': 'status_user_twitter',
                'managed': False,
                'verbose_name_plural': 'Users statuses',
            },
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tweet', models.BigIntegerField(unique=True)),
                ('id_user', models.BigIntegerField()),
                ('name_author', models.CharField(blank=True, max_length=150, null=True)),
                ('name_screen', models.CharField(max_length=150)),
                ('text_tweet', models.CharField(max_length=400)),
                ('create_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('geo', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('lang', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'managed': False,
                'ordering': ['-id_tweet'],
                'verbose_name_plural': 'Tweets',
                'db_table': 'tweets',
                'verbose_name': 'Tweet',
            },
        ),
        migrations.CreateModel(
            name='UserTwitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('consumer_key', models.CharField(max_length=50)),
                ('consumer_secret', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
                ('access_token_secret', models.CharField(max_length=100)),
                ('count_use', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'User twitter',
                'db_table': 'user_twitter',
                'managed': False,
                'verbose_name_plural': 'Users twitter',
            },
        ),
    ]
